stages:
  - deploy

deploy-code-job:
  stage: deploy
  only: ["main"]
  image: docker:20.10.16
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: "my-front"
  before_script:
    - apk update && apk add openssh-client
  script:
    - echo "$SSH_PRIVATE_KEY" > ssh_key
    - chmod 600 ssh_key
    - ssh -o StrictHostKeyChecking=no -i ssh_key "$USER_SERVER@$IP_SERVER" "echo Connected"
    - docker build --build-arg VITE_BASE_URL="$VITE_BASE_URL" -t "$IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker save "$IMAGE_NAME:$CI_COMMIT_SHA" | ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker load"
    - ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker container rm -f $IMAGE_NAME || true"
    - ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker run -d --restart always --name $IMAGE_NAME -p 80:80 $IMAGE_NAME:$CI_COMMIT_SHA"
  after_script:
    - |
      if [ -n "$CI_COMMIT_BEFORE_SHA" ]; then
        PREVIOUS_IMAGE="$IMAGE_NAME:$CI_COMMIT_BEFORE_SHA"
        ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker image rm $PREVIOUS_IMAGE || true"
      fi
    - ls -la
    - rm -f ssh_key

#stages:
#  - deploy
#
#deploy-code-job:
#  stage: deploy
#  image: docker:20.10.16
#  services:
#    - docker:dind
#  variables:
#    DOCKER_DRIVER: overlay2
#    IMAGE_NAME: "my-front"
#  before_script:
#    - apk update && apk add openssh-client
#  script:
#    - echo "$SSH_PRIVATE_KEY" > ssh_key
#    - chmod 600 ssh_key
#    - ssh -o StrictHostKeyChecking=no -i ssh_key "$USER_SERVER@$IP_SERVER" "echo Connected"
#    - docker build --build-arg VITE_BASE_URL="$VITE_BASE_URL" -t "$IMAGE_NAME:$CI_COMMIT_SHA" .
#    - docker save "$IMAGE_NAME:$CI_COMMIT_SHA" | ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker load"
#    - ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker container rm -f $IMAGE_NAME || true"
#    - ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker run -d --restart always --name $IMAGE_NAME -p 80:80 $IMAGE_NAME:$CI_COMMIT_SHA"
#  after_script:
#    - ssh -i ssh_key "$USER_SERVER@$IP_SERVER" "docker image prune -a -f"
#    - ls -la
#    - rm -f ssh_key